require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HandbookJobpositionsController do

  # This should return the minimal set of attributes required to create a valid
  # HandbookJobposition. As you add validations to HandbookJobposition, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HandbookJobpositionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all handbook_jobpositions as @handbook_jobpositions" do
      handbook_jobposition = HandbookJobposition.create! valid_attributes
      get :index, {}, valid_session
      assigns(:handbook_jobpositions).should eq([handbook_jobposition])
    end
  end

  describe "GET show" do
    it "assigns the requested handbook_jobposition as @handbook_jobposition" do
      handbook_jobposition = HandbookJobposition.create! valid_attributes
      get :show, {:id => handbook_jobposition.to_param}, valid_session
      assigns(:handbook_jobposition).should eq(handbook_jobposition)
    end
  end

  describe "GET new" do
    it "assigns a new handbook_jobposition as @handbook_jobposition" do
      get :new, {}, valid_session
      assigns(:handbook_jobposition).should be_a_new(HandbookJobposition)
    end
  end

  describe "GET edit" do
    it "assigns the requested handbook_jobposition as @handbook_jobposition" do
      handbook_jobposition = HandbookJobposition.create! valid_attributes
      get :edit, {:id => handbook_jobposition.to_param}, valid_session
      assigns(:handbook_jobposition).should eq(handbook_jobposition)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HandbookJobposition" do
        expect {
          post :create, {:handbook_jobposition => valid_attributes}, valid_session
        }.to change(HandbookJobposition, :count).by(1)
      end

      it "assigns a newly created handbook_jobposition as @handbook_jobposition" do
        post :create, {:handbook_jobposition => valid_attributes}, valid_session
        assigns(:handbook_jobposition).should be_a(HandbookJobposition)
        assigns(:handbook_jobposition).should be_persisted
      end

      it "redirects to the created handbook_jobposition" do
        post :create, {:handbook_jobposition => valid_attributes}, valid_session
        response.should redirect_to(HandbookJobposition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved handbook_jobposition as @handbook_jobposition" do
        # Trigger the behavior that occurs when invalid params are submitted
        HandbookJobposition.any_instance.stub(:save).and_return(false)
        post :create, {:handbook_jobposition => {}}, valid_session
        assigns(:handbook_jobposition).should be_a_new(HandbookJobposition)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HandbookJobposition.any_instance.stub(:save).and_return(false)
        post :create, {:handbook_jobposition => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested handbook_jobposition" do
        handbook_jobposition = HandbookJobposition.create! valid_attributes
        # Assuming there are no other handbook_jobpositions in the database, this
        # specifies that the HandbookJobposition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HandbookJobposition.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => handbook_jobposition.to_param, :handbook_jobposition => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested handbook_jobposition as @handbook_jobposition" do
        handbook_jobposition = HandbookJobposition.create! valid_attributes
        put :update, {:id => handbook_jobposition.to_param, :handbook_jobposition => valid_attributes}, valid_session
        assigns(:handbook_jobposition).should eq(handbook_jobposition)
      end

      it "redirects to the handbook_jobposition" do
        handbook_jobposition = HandbookJobposition.create! valid_attributes
        put :update, {:id => handbook_jobposition.to_param, :handbook_jobposition => valid_attributes}, valid_session
        response.should redirect_to(handbook_jobposition)
      end
    end

    describe "with invalid params" do
      it "assigns the handbook_jobposition as @handbook_jobposition" do
        handbook_jobposition = HandbookJobposition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HandbookJobposition.any_instance.stub(:save).and_return(false)
        put :update, {:id => handbook_jobposition.to_param, :handbook_jobposition => {}}, valid_session
        assigns(:handbook_jobposition).should eq(handbook_jobposition)
      end

      it "re-renders the 'edit' template" do
        handbook_jobposition = HandbookJobposition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HandbookJobposition.any_instance.stub(:save).and_return(false)
        put :update, {:id => handbook_jobposition.to_param, :handbook_jobposition => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested handbook_jobposition" do
      handbook_jobposition = HandbookJobposition.create! valid_attributes
      expect {
        delete :destroy, {:id => handbook_jobposition.to_param}, valid_session
      }.to change(HandbookJobposition, :count).by(-1)
    end

    it "redirects to the handbook_jobpositions list" do
      handbook_jobposition = HandbookJobposition.create! valid_attributes
      delete :destroy, {:id => handbook_jobposition.to_param}, valid_session
      response.should redirect_to(handbook_jobpositions_url)
    end
  end

end
