require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HandbookDocumentMarksController do

  # This should return the minimal set of attributes required to create a valid
  # HandbookDocumentMark. As you add validations to HandbookDocumentMark, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HandbookDocumentMarksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all handbook_document_marks as @handbook_document_marks" do
      handbook_document_mark = HandbookDocumentMark.create! valid_attributes
      get :index, {}, valid_session
      assigns(:handbook_document_marks).should eq([handbook_document_mark])
    end
  end

  describe "GET show" do
    it "assigns the requested handbook_document_mark as @handbook_document_mark" do
      handbook_document_mark = HandbookDocumentMark.create! valid_attributes
      get :show, {:id => handbook_document_mark.to_param}, valid_session
      assigns(:handbook_document_mark).should eq(handbook_document_mark)
    end
  end

  describe "GET new" do
    it "assigns a new handbook_document_mark as @handbook_document_mark" do
      get :new, {}, valid_session
      assigns(:handbook_document_mark).should be_a_new(HandbookDocumentMark)
    end
  end

  describe "GET edit" do
    it "assigns the requested handbook_document_mark as @handbook_document_mark" do
      handbook_document_mark = HandbookDocumentMark.create! valid_attributes
      get :edit, {:id => handbook_document_mark.to_param}, valid_session
      assigns(:handbook_document_mark).should eq(handbook_document_mark)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HandbookDocumentMark" do
        expect {
          post :create, {:handbook_document_mark => valid_attributes}, valid_session
        }.to change(HandbookDocumentMark, :count).by(1)
      end

      it "assigns a newly created handbook_document_mark as @handbook_document_mark" do
        post :create, {:handbook_document_mark => valid_attributes}, valid_session
        assigns(:handbook_document_mark).should be_a(HandbookDocumentMark)
        assigns(:handbook_document_mark).should be_persisted
      end

      it "redirects to the created handbook_document_mark" do
        post :create, {:handbook_document_mark => valid_attributes}, valid_session
        response.should redirect_to(HandbookDocumentMark.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved handbook_document_mark as @handbook_document_mark" do
        # Trigger the behavior that occurs when invalid params are submitted
        HandbookDocumentMark.any_instance.stub(:save).and_return(false)
        post :create, {:handbook_document_mark => {}}, valid_session
        assigns(:handbook_document_mark).should be_a_new(HandbookDocumentMark)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HandbookDocumentMark.any_instance.stub(:save).and_return(false)
        post :create, {:handbook_document_mark => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested handbook_document_mark" do
        handbook_document_mark = HandbookDocumentMark.create! valid_attributes
        # Assuming there are no other handbook_document_marks in the database, this
        # specifies that the HandbookDocumentMark created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HandbookDocumentMark.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => handbook_document_mark.to_param, :handbook_document_mark => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested handbook_document_mark as @handbook_document_mark" do
        handbook_document_mark = HandbookDocumentMark.create! valid_attributes
        put :update, {:id => handbook_document_mark.to_param, :handbook_document_mark => valid_attributes}, valid_session
        assigns(:handbook_document_mark).should eq(handbook_document_mark)
      end

      it "redirects to the handbook_document_mark" do
        handbook_document_mark = HandbookDocumentMark.create! valid_attributes
        put :update, {:id => handbook_document_mark.to_param, :handbook_document_mark => valid_attributes}, valid_session
        response.should redirect_to(handbook_document_mark)
      end
    end

    describe "with invalid params" do
      it "assigns the handbook_document_mark as @handbook_document_mark" do
        handbook_document_mark = HandbookDocumentMark.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HandbookDocumentMark.any_instance.stub(:save).and_return(false)
        put :update, {:id => handbook_document_mark.to_param, :handbook_document_mark => {}}, valid_session
        assigns(:handbook_document_mark).should eq(handbook_document_mark)
      end

      it "re-renders the 'edit' template" do
        handbook_document_mark = HandbookDocumentMark.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HandbookDocumentMark.any_instance.stub(:save).and_return(false)
        put :update, {:id => handbook_document_mark.to_param, :handbook_document_mark => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested handbook_document_mark" do
      handbook_document_mark = HandbookDocumentMark.create! valid_attributes
      expect {
        delete :destroy, {:id => handbook_document_mark.to_param}, valid_session
      }.to change(HandbookDocumentMark, :count).by(-1)
    end

    it "redirects to the handbook_document_marks list" do
      handbook_document_mark = HandbookDocumentMark.create! valid_attributes
      delete :destroy, {:id => handbook_document_mark.to_param}, valid_session
      response.should redirect_to(handbook_document_marks_url)
    end
  end

end
