require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HandbookDivisionsController do

  # This should return the minimal set of attributes required to create a valid
  # HandbookDivision. As you add validations to HandbookDivision, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HandbookDivisionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all handbook_divisions as @handbook_divisions" do
      handbook_division = HandbookDivision.create! valid_attributes
      get :index, {}, valid_session
      assigns(:handbook_divisions).should eq([handbook_division])
    end
  end

  describe "GET show" do
    it "assigns the requested handbook_division as @handbook_division" do
      handbook_division = HandbookDivision.create! valid_attributes
      get :show, {:id => handbook_division.to_param}, valid_session
      assigns(:handbook_division).should eq(handbook_division)
    end
  end

  describe "GET new" do
    it "assigns a new handbook_division as @handbook_division" do
      get :new, {}, valid_session
      assigns(:handbook_division).should be_a_new(HandbookDivision)
    end
  end

  describe "GET edit" do
    it "assigns the requested handbook_division as @handbook_division" do
      handbook_division = HandbookDivision.create! valid_attributes
      get :edit, {:id => handbook_division.to_param}, valid_session
      assigns(:handbook_division).should eq(handbook_division)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HandbookDivision" do
        expect {
          post :create, {:handbook_division => valid_attributes}, valid_session
        }.to change(HandbookDivision, :count).by(1)
      end

      it "assigns a newly created handbook_division as @handbook_division" do
        post :create, {:handbook_division => valid_attributes}, valid_session
        assigns(:handbook_division).should be_a(HandbookDivision)
        assigns(:handbook_division).should be_persisted
      end

      it "redirects to the created handbook_division" do
        post :create, {:handbook_division => valid_attributes}, valid_session
        response.should redirect_to(HandbookDivision.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved handbook_division as @handbook_division" do
        # Trigger the behavior that occurs when invalid params are submitted
        HandbookDivision.any_instance.stub(:save).and_return(false)
        post :create, {:handbook_division => {}}, valid_session
        assigns(:handbook_division).should be_a_new(HandbookDivision)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HandbookDivision.any_instance.stub(:save).and_return(false)
        post :create, {:handbook_division => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested handbook_division" do
        handbook_division = HandbookDivision.create! valid_attributes
        # Assuming there are no other handbook_divisions in the database, this
        # specifies that the HandbookDivision created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HandbookDivision.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => handbook_division.to_param, :handbook_division => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested handbook_division as @handbook_division" do
        handbook_division = HandbookDivision.create! valid_attributes
        put :update, {:id => handbook_division.to_param, :handbook_division => valid_attributes}, valid_session
        assigns(:handbook_division).should eq(handbook_division)
      end

      it "redirects to the handbook_division" do
        handbook_division = HandbookDivision.create! valid_attributes
        put :update, {:id => handbook_division.to_param, :handbook_division => valid_attributes}, valid_session
        response.should redirect_to(handbook_division)
      end
    end

    describe "with invalid params" do
      it "assigns the handbook_division as @handbook_division" do
        handbook_division = HandbookDivision.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HandbookDivision.any_instance.stub(:save).and_return(false)
        put :update, {:id => handbook_division.to_param, :handbook_division => {}}, valid_session
        assigns(:handbook_division).should eq(handbook_division)
      end

      it "re-renders the 'edit' template" do
        handbook_division = HandbookDivision.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HandbookDivision.any_instance.stub(:save).and_return(false)
        put :update, {:id => handbook_division.to_param, :handbook_division => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested handbook_division" do
      handbook_division = HandbookDivision.create! valid_attributes
      expect {
        delete :destroy, {:id => handbook_division.to_param}, valid_session
      }.to change(HandbookDivision, :count).by(-1)
    end

    it "redirects to the handbook_divisions list" do
      handbook_division = HandbookDivision.create! valid_attributes
      delete :destroy, {:id => handbook_division.to_param}, valid_session
      response.should redirect_to(handbook_divisions_url)
    end
  end

end
